/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.controladorClienteFijo;
import ec.edu.ups.controlador.controladorEspacios;
import ec.edu.ups.controlador.controladorTicketCliente;
import ec.edu.ups.modelo.ClienteFijo;
import ec.edu.ups.modelo.TicketClienteMomentaneo;
import java.io.IOException;
import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class ConsultaMulta extends javax.swing.JInternalFrame {

    private controladorEspacios controladorEspacios;
    private controladorClienteFijo controladorClienteFijo;
    private controladorTicketCliente controladorTicketCliente;

    public ConsultaMulta(controladorEspacios controladorEspacios, controladorClienteFijo controladorClienteFijo, controladorTicketCliente controladorTicketCliente) {
        initComponents();
        this.controladorEspacios = controladorEspacios;
        this.controladorClienteFijo = controladorClienteFijo;
        this.controladorTicketCliente = controladorTicketCliente;
        
        try {
            controladorEspacios.cargarDatos();
            controladorClienteFijo.cargarDatos();
            controladorTicketCliente.cargarDatos();
        } catch (ClassNotFoundException | IOException ex) {
            Logger.getLogger(ConsultaMulta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        txtConsulta = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setTitle("Consultar Multas");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingrese Numero de Espacio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanel5.setToolTipText("");
        jPanel5.setName(""); // NOI18N

        txtConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(59, 59, 59)
                .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        btnConsultar.setText("CONSULTAR");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("LIMPIAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConsultar)
                        .addGap(53, 53, 53)
                        .addComponent(btnLimpiar)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnLimpiar))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsultaActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        if (txtConsulta.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "CAMPO VACIO");
        } else {
            String r = controladorEspacios.buscarEspacioAsignado(Integer.parseInt(txtConsulta.getText().trim()));

            if (r.equals("")) {
                JOptionPane.showMessageDialog(this, "El espacio solicitado no cuenta con algún tipo de servicio de arrendamiento o multa");
            } else {
                int id = Integer.parseInt(r);

                ClienteFijo comparar = new ClienteFijo(id, null, null, null, null, 0, null, null, null, null, null);

                TicketClienteMomentaneo comp = new TicketClienteMomentaneo();

                comp.setId(id);

                Optional<ClienteFijo> a = controladorClienteFijo.buscar(comparar);

                Optional<TicketClienteMomentaneo> b = controladorTicketCliente.buscar(comp);

                ClienteFijo c = a.get();

                TicketClienteMomentaneo d = b.get();

                if (c != null) {
                    JOptionPane.showMessageDialog(this, "El espacio solicitado esta ocupado por " + c.getNombre() + " " + c.getApellido());
                    if (c.getMulta() > 0) {
                        JOptionPane.showMessageDialog(this, "Tiene una multa de " + c.getMulta());
                    }
                } else if (d != null) {

                    JOptionPane.showMessageDialog(this, "El espacio solicitado esta ocupado por " + d.getNombre() + " ");
                    if (c.getMulta() > 0) {
                        JOptionPane.showMessageDialog(this, "Tiene una multa de " + d.getMulta());
                    }
                }

            }
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txtConsulta;
    // End of variables declaration//GEN-END:variables
}
