/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;





/**
 *
 * @author user
 */
public class VentanaPrincipal extends javax.swing.JFrame {

   

    public VentanaPrincipal() {
        initComponents();

        
        
        
        
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        ArchivosMenu = new javax.swing.JMenu();
        VerTablasMenu = new javax.swing.JMenu();
        TarifasMenuItem = new javax.swing.JMenuItem();
        UsuariosMenuItem = new javax.swing.JMenuItem();
        RegistrosMonetariosMenuItem = new javax.swing.JMenuItem();
        IniciarSesionMenuItem = new javax.swing.JMenuItem();
        CerrarSesionMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);
        getContentPane().setLayout(new java.awt.FlowLayout());

        desktopPane.setLayout(new java.awt.BorderLayout());
        getContentPane().add(desktopPane);

        ArchivosMenu.setMnemonic('f');
        ArchivosMenu.setText("Inicio");

        VerTablasMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/vista/verTablas.png"))); // NOI18N
        VerTablasMenu.setText("Ver Tablas");

        TarifasMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        TarifasMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/vista/Tarifas.png"))); // NOI18N
        TarifasMenuItem.setText("Tarifas");
        TarifasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TarifasMenuItemActionPerformed(evt);
            }
        });
        VerTablasMenu.add(TarifasMenuItem);

        UsuariosMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        UsuariosMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/vista/user.png"))); // NOI18N
        UsuariosMenuItem.setText("Usuarios");
        UsuariosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuariosMenuItemActionPerformed(evt);
            }
        });
        VerTablasMenu.add(UsuariosMenuItem);

        ArchivosMenu.add(VerTablasMenu);

        RegistrosMonetariosMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        RegistrosMonetariosMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/vista/moneda.png"))); // NOI18N
        RegistrosMonetariosMenuItem.setMnemonic('s');
        RegistrosMonetariosMenuItem.setText("Registros Monetarios");
        RegistrosMonetariosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrosMonetariosMenuItemActionPerformed(evt);
            }
        });
        ArchivosMenu.add(RegistrosMonetariosMenuItem);

        IniciarSesionMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        IniciarSesionMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/vista/Log.png"))); // NOI18N
        IniciarSesionMenuItem.setText("Iniciar Sesion");
        IniciarSesionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSesionMenuItemActionPerformed(evt);
            }
        });
        ArchivosMenu.add(IniciarSesionMenuItem);

        CerrarSesionMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        CerrarSesionMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/vista/logOut.png"))); // NOI18N
        CerrarSesionMenuItem.setText("Cerrar Sesion");
        CerrarSesionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionMenuItemActionPerformed(evt);
            }
        });
        ArchivosMenu.add(CerrarSesionMenuItem);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/vista/Salir.png"))); // NOI18N
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        ArchivosMenu.add(exitMenuItem);

        menuBar.add(ArchivosMenu);

        setJMenuBar(menuBar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void CerrarSesionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionMenuItemActionPerformed
       

    }//GEN-LAST:event_CerrarSesionMenuItemActionPerformed

    private void IniciarSesionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesionMenuItemActionPerformed
       
    }//GEN-LAST:event_IniciarSesionMenuItemActionPerformed

    private void UsuariosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuariosMenuItemActionPerformed
       
    }//GEN-LAST:event_UsuariosMenuItemActionPerformed

    private void TarifasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TarifasMenuItemActionPerformed
       
    }//GEN-LAST:event_TarifasMenuItemActionPerformed

    private void RegistrosMonetariosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrosMonetariosMenuItemActionPerformed
        
    }//GEN-LAST:event_RegistrosMonetariosMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ArchivosMenu;
    private javax.swing.JMenuItem CerrarSesionMenuItem;
    private javax.swing.JMenuItem IniciarSesionMenuItem;
    private javax.swing.JMenuItem RegistrosMonetariosMenuItem;
    private javax.swing.JMenuItem TarifasMenuItem;
    private javax.swing.JMenuItem UsuariosMenuItem;
    private javax.swing.JMenu VerTablasMenu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
